#!/usr/bin/env bash
# Does the following:
#   it Create a file /var/run/myscript.pid containing the script PID.
#   it Displays "To infinity and beyond" indefinitely
#   it Displays "I hate the kill command" upon receiving a SIGTERM
#   it Displays "Y U no love me?!" upon receiving a SIGINT
#   it Deletes the file /var/run/mycript.pid and terminates upon
#+  also receiving a SIGQUIT or SIGTERM.

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
