#!/usr/bin/env bash
# it displays To infinity and beyond indefinitely
# it does it With a sleep 2 in between each iteration
# It is therefore invincible!!! when receiving a SIGTERM signal

while true
do 
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
