#!/usr/bin/env bash
# It will display the content of the file /etc/passwd.
# The script should only display:
#    the username
#    the user id
#    the Home directory path for the user
while read -r line; do
    echo "$line" | cut -d ':' -f 1,3,6
done</etc/passwd
