#!/usr/bin/env bash
# It Displays:
#  Content of the current directory
#  that is in a list format
#  in which only the part of the name after the first dash is displayed

for f in *; do
    echo "$f" | cut -d '-' -f 2

done
